jdk: openjdk8
language: groovy

branches:
  only:
  - /.*/

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_80297b79dae4_key -iv $encrypted_80297b79dae4_iv
          -in gradle.properties.enc -out gradle.properties -d;
    fi

script: ./buildViaTravis.sh


before_deploy: ./gradlew dokka
deploy:
   provider: pages
   skip-cleanup: true
   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
   keep-history: true
   on:
     branch: master
   local-dir: build/docs/openrndr
   target-branch: gh-pages
